version: '3.8'
services:
  smart-farm-db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smartfarmdb
    ports:
      - '15444:5432' # Ánh xạ cổng local 15444 sang cổng 5432 trong container
    volumes:
      - pgdata:/var/lib/postgresql/data
    # Tùy chọn: thêm label để quản lý container
    labels:
      - 'app=smart-farm-db'

  smart-farm-server:
    build: .
    restart: always
    depends_on:
      - smart-farm-db
    ports:
      - '3456:3000' # Ứng dụng lắng nghe trên cổng 3000
    environment:
      # Sử dụng hostname của service smart-farm-db trong mạng docker-compose
      DATABASE_URL: 'postgresql://user:postgres@smart-farm-db:5432/smartfarmdb?schema=public'
    command: npm run start:prod
    labels:
      - 'app=smart-farm-server'

volumes:
  pgdata:
