version: '3.8'

services:
  smart-garden-db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smartgardendb
    ports:
      - '15444:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user -d smartgardendb']
      interval: 10s
      retries: 5
    labels:
      - app=smart-garden-db

  smart-garden-server:
    build: .
    restart: always
    depends_on:
      smart-garden-db:
        condition: service_healthy
    ports:
      - '3456:3000'
    environment:
      DATABASE_URL: postgresql://user:postgres@smart-garden-db:5432/smartgardendb?schema=public
    labels:
      - app=smart-garden-server
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'curl -f http://localhost:3456/v1/health/liveness || exit 1',
        ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  pgdata:
